name: Devops Workflow

on:
  push:
    branches:
       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout de Código 
        uses: actions/checkout@v6 #baixa todo código do repo na maquina virtual

      - name: Mostrar Mensagem
        run: echo "Olá, Mundo Devops!"